### ISSUE TITLE
Add support for [env] in the dorfile

### ISSUE THREAD

**Issue by daonb** [tuzig/terminal7#133]
**What's missing? Please describe your flow and where this feature will help.**
I want to set $TERM for start every new shell. The dotfile will have:

```toml

[env]
TERM=xterm
COLORTERM=truecolor
HELLO=WORLD

```

**Additional context**

This is based on a user request: her tools weren't displaying properly so she `echo $TERM` and found it was unset.

This is a big change as existing users will want to update their dotfile. We need to notify the user of the new settings and invite them to edit it in.
